# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true

# Enables non-transitive R classes to reduce app size
android.nonTransitiveRClass=true

# Suppress unsupported compileSdk warnings/errors for compileSdk 35
android.suppressUnsupportedCompileSdk=35
